-- Optional examples after login.
-- This version uses RPC functions, so most seed actions are best done from admin.html.
-- You may use p112_bootstrap_sysadmin() first, then log in and create units/users from the web UI.
